//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Modules.Repl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Modules.Repl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_CSharp {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_CSharp_Scripting {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_CSharp_Scripting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.CodeAnalysis.CSharp.Scripting&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript&quot;&gt;
        ///            &lt;summary&gt;
        ///            A factory for creating and running C# scripts.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.Create``1(System.String,Microsoft.CodeAnalysis.Scripting.ScriptOptions,System.Type,Micros [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_CodeAnalysis_CSharp_Scripting1 {
            get {
                return ResourceManager.GetString("Microsoft_CodeAnalysis_CSharp_Scripting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.CodeAnalysis.CSharp&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.CodeAnalysis.CSharp.Binder&quot;&gt;
        ///            &lt;summary&gt;
        ///            A Binder converts names in to symbols and syntax nodes into bound trees. It is context
        ///            dependent, relative to a location in source code.
        ///            &lt;/summary&gt;
        ///            &lt;summary&gt;
        ///            This portion of the binder converts a AnonymousObjectCreationExpressionSy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_CodeAnalysis_CSharp1 {
            get {
                return ResourceManager.GetString("Microsoft_CodeAnalysis_CSharp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_Scripting {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_Scripting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.CodeAnalysis.Scripting&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;M:Microsoft.CodeAnalysis.RelativePathResolver.#ctor(System.Collections.Immutable.ImmutableArray{System.String},System.String)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Initializes a new instance of the &lt;see cref=&quot;T:Microsoft.CodeAnalysis.RelativePathResolver&quot;/&gt; class.
        ///            &lt;/summary&gt;
        ///            &lt;param name=&quot;searchPaths&quot;&gt;An ordered set of fully quali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_CodeAnalysis_Scripting1 {
            get {
                return ResourceManager.GetString("Microsoft_CodeAnalysis_Scripting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.CodeAnalysis&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager&quot;&gt;
        ///            &lt;summary&gt;
        ///            Manages properties of analyzers (such as registered actions, supported diagnostics) for analyzer host&apos;s lifetime
        ///            and executes the callbacks into the analyzers.
        ///            
        ///            It ensures the following for the lifetime of analyzer host:
        ///            1)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_CodeAnalysis1 {
            get {
                return ResourceManager.GetString("Microsoft_CodeAnalysis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] REPL {
            get {
                object obj = ResourceManager.GetObject("REPL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot; /&gt;
        ///    &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.IO.Compression&quot; publicKeyToken=&quot;b77a5c561934e089&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirect oldVersion=&quot;0.0.0.0-4.1.0.0&quot; newVersion=&quot;4.1.0.0&quot; /&gt;
        ///      &lt;/dependentAssembly&gt;
        ///      &lt;dependentAssem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REPL_exe {
            get {
                return ResourceManager.GetString("REPL_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] REPL_vshost {
            get {
                object obj = ResourceManager.GetObject("REPL_vshost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.6.1&quot; /&gt;
        ///    &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.IO.Compression&quot; publicKeyToken=&quot;b77a5c561934e089&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirect oldVersion=&quot;0.0.0.0-4.1.0.0&quot; newVersion=&quot;4.1.0.0&quot; /&gt;
        ///      &lt;/dependentAssembly&gt;
        ///      &lt;dependentAssem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REPL_vshost_exe {
            get {
                return ResourceManager.GetString("REPL_vshost_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] REPL_vshost_exe1 {
            get {
                object obj = ResourceManager.GetObject("REPL_vshost_exe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] REPL1 {
            get {
                object obj = ResourceManager.GetObject("REPL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_AppContext {
            get {
                object obj = ResourceManager.GetObject("System_AppContext", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Collections_Immutable {
            get {
                object obj = ResourceManager.GetObject("System_Collections_Immutable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.Collections.Immutable&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Collections.Generic.IHashKeyCollection`1&quot;&gt;
        ///            &lt;summary&gt;
        ///            Defined on a generic collection that hashes its contents using an &lt;see cref=&quot;T:System.Collections.Generic.IEqualityComparer`1&quot;/&gt;.
        ///            &lt;/summary&gt;
        ///            &lt;typeparam name=&quot;TKey&quot;&gt;The type of element hashed in the collection.&lt;/typeparam&gt;
        ///        &lt;/member&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Collections_Immutable1 {
            get {
                return ResourceManager.GetString("System_Collections_Immutable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Console {
            get {
                object obj = ResourceManager.GetObject("System_Console", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Diagnostics_FileVersionInfo {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_FileVersionInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Diagnostics_StackTrace {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_StackTrace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_Compression {
            get {
                object obj = ResourceManager.GetObject("System_IO_Compression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_FileSystem {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_FileSystem_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Reflection_Metadata {
            get {
                object obj = ResourceManager.GetObject("System_Reflection_Metadata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.Reflection.Metadata&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Reflection.Internal.AbstractMemoryBlock&quot;&gt;
        ///            &lt;summary&gt;
        ///            Represents a disposable blob of memory accessed via unsafe pointer.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;P:System.Reflection.Internal.AbstractMemoryBlock.Pointer&quot;&gt;
        ///            &lt;summary&gt;
        ///            Pointer to the underlying data (not valid after [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Reflection_Metadata1 {
            get {
                return ResourceManager.GetString("System_Reflection_Metadata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Runtime_InteropServices_RuntimeInformation {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_InteropServices_RuntimeInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Algorithms {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Algorithms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Encoding {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Encoding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_X509Certificates {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_X509Certificates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encoding_CodePages {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encoding_CodePages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Threading_Thread {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Thread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XmlDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XmlDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XPath {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XPath_XDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath_XDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
